name: KONG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  KONG:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Get KONG
        run: |
          git clone https://${{ secrets.KONG_REPO_PAT }}@github.com/statsig-io/kong.git

      - name: Setup PHP Server
        run: |
          cd kong/bridges/php-server
          composer config --auth github-oauth.github.com ${{ secrets.KONG_REPO_PAT }}
          BRANCH="${GITHUB_HEAD_REF:-main}"; composer config repositories.0 "{\"type\": \"vcs\", \"url\": \"git@github.com:$GITHUB_REPOSITORY.git\", \"trunk-path\": \"$BRANCH\"}"
          cat composer.json
          composer update
          BRANCH="${GITHUB_HEAD_REF:-main}"; composer require statsig/statsigsdk dev-$BRANCH

      - name: Run Tests
        run: |
          cd kong
          npm install
          FORCE_COLOR=true npm run kong -- test php -w -r -f rulesets
        env:
          test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}
          test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}
